(defun parse-move (board move mark)
  (let ((x (/ (- move (mod move 10)) 10)) 
	(y (mod move 10)))
    (if (and (< x 3) (< y 3) 
	 (eql (aref board x y) nil)) 
	(setf (aref board x y) mark))))

(defun prompt-move (player)
  (format *query-io* "~%~a's move: " player)
  (force-output *query-io*)
  (read-line *query-io*))

(defun print-board (board)
  (dotimes (i 3)
    (format t " .---.---.---. ~% | ")
    (dotimes (j 3)
      (if (eql (aref board i j) nil)
	  (format t " ")
	  (format t "~a" (aref board i j)))
      (format t " | "))
    (format t "~%"))
  (format t " '---'---'---'"))

(defun board-init (size)
  (defvar board nil)
  (setf board (make-array (list size size) :initial-element nil)))

(defun board-game-run (board)
  (dotimes (i (array-total-size board))
    (print-board board)
    (let ((player 0) (mark 0))
      (if (eql (mod i 2) 0)
	  (progn
	    (setq player 1) 
	    (setq mark #\X))
	  (progn
	    (setq player 2)
	    (setq mark #\0)))
      (loop until
	     (parse-move board (parse-integer (prompt-move player)) mark))))
  (print-board board))
